### ISSUE TITLE
Option for desktop browsers only

### ISSUE THREAD

**Issue by akavlie** [h5bp/html5please-api#66] opened 2012-05-08 23:35 UTC
The API lists iOS Safari among the suggested browsers. This doesn't look right to me, if the goal is to give the user links to browsers they can upgrade to.

There should be an option to limit results to desktop browsers only.

**Comment by drublic** [comment] 2012-05-13 23:13
This is totally right. The API is supposed to list only browsers that are supported on a specific OS. For instance we don't want to suggest IE if you're on a Mac.

It would be great if you could provide a short test-case for this issue.
Thank you!

**Comment by akavlie** [comment] 2012-05-13 23:21
I could take a stab at that... assuming you've done dev work on this, could you point me in the right direction? Is there already code for selecting browser links based on OS?

I'm not sure there's any situation where iOS Safari would be relevant -- it can't be installed on its own. Info about minimum OS version would make more sense on mobile.

**Comment by drublic** [comment] 2012-05-14 23:27
The OS should be detected automatically by the API. You don't need set a param for this.
I've [created a test-case](http://jsfiddle.net/drublic/CazFu/) which reproduces this issue. On Chrome only Opera Mobile is offered as an alternative the "stream".

I'll try to figure out what the problem is in the next days.

**Comment by addyosmani** [comment] 2012-06-09 17:56
@drublic do you think you might have the bandwidth to chase this up?

**Comment by drublic** [comment] 2012-06-10 11:17
@addyosmani, thanks for the reminder. And sorry, for the missing update.

This problem is now fixed with the last commit I. When implementing the "partial"-support I forgot to filter the results by the type of the OS. I've now implemented it (was just 1 LoC).
Please let me know if there are further problems with detecting the type.

**Closed as completed by drublic** 2012-06-10 11:17 UTC

**Comment by addyosmani** [comment] 2012-06-10 11:29
@drublic Perfect. Thank you for working on this so quickly!
